### ISSUE TITLE
What-to-do

### ISSUE THREAD

**Issue by artginzburg** [eurogym-cs-dp-2018-2020/EGfoodmenu#1]
1. DB for dishes
- [ ] Название
- [ ] Вес
- [ ] Категория

2. Key features
- [ ] Все приёмы пищи отображаются на одной странице, с возможностью менять день
- [ ] Если меню за будущие числа не заполнено, данные туда подтягиваются с того же дня прошлой недели, и уведомление где-то на странице говорит об этом

3. Functions (user)
- [ ] Выбрать день недели
- [ ] История

4. Functions (admin)
- [ ] Добавлять блюда в общий список
- [ ] Раскидывать блюда по обеду, ужину, завтраку (драг&дропом?)
- [ ] Выбирать день недели
